In [21]:
import pandas as pd
import numpy as np

In [2]:
rating_data = pd.read_csv('data/ratings.csv')

In [3]:
movie_data = pd.read_csv('data/movies.csv')

In [4]:
rating_data.head()

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [5]:
movie_data.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [6]:
rating_data.drop('timestamp', axis=1, inplace=True)

In [8]:
rating_movie_data = pd.merge(rating_data, movie_data, on='movieId')

In [28]:
user_movie_rating = rating_movie_data.pivot_table('rating', index='userId', columns='title').fillna(0)

In [29]:
user_movie_rating.head()

title   "Great Performances" Cats (1998)  $9.99 (2008)  \
userId                                                   
1                                    0.0           0.0   
2                                    0.0           0.0   
3                                    0.0           0.0   
4                                    0.0           0.0   
5                                    0.0           0.0   

title   'Hellboy': The Seeds of Creation (2004)  \
userId                                            
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
5                                           0.0   

title   'Neath the Arizona Skies (1934)  'Round Midnight (1986)  \
userId                                                            
1                                   0.0                     0.0   
2                                   0.0                     0.0   
3                                   0.0                     0.0   
4                                   0.0                     0.0   
5                                   0.0                     0.0   

title   'Salem's Lot (2004)  'Til There Was You (1997)  'burbs, The (1989)  \
userId                                                                       
1                       0.0                        0.0                 0.0   
2                       0.0                        0.0                 0.0   
3                       0.0                        0.0                 0.0   
4                       0.0                        0.0                 0.0   
5                       0.0                        0.0                 0.0   

title   'night Mother (1986)  (500) Days of Summer (2009)  ...  Zulu (1964)  \
userId                                                     ...                
1                        0.0                          0.0  ...          0.0   
2                        0.0                          0.0  ...          0.0   
3                        0.0                          0.0  ...          0.0   
4                        0.0                          0.0  ...          0.0   
5                        0.0                          0.0  ...          0.0   

title   Zulu (2013)  [REC] (2007)  eXistenZ (1999)  \
userId                                               
1               0.0           0.0              0.0   
2               0.0           0.0              0.0   
3               0.0           0.0              0.0   
4               0.0           0.0              0.0   
5               0.0           0.0              0.0   

title   loudQUIETloud: A Film About the Pixies (2006)  xXx (2002)  \
userId                                                              
1                                                 0.0         0.0   
2                                                 0.0         0.0   
3                                                 0.0         0.0   
4                                                 0.0         0.0   
5                                                 0.0         0.0   

title   xXx: State of the Union (2005)  ¡Three Amigos! (1986)  \
userId                                                          
1                                  0.0                    0.0   
2                                  0.0                    0.0   
3                                  0.0                    0.0   
4                                  0.0                    0.0   
5                                  0.0                    0.0   

title   À nous la liberté (Freedom for Us) (1931)  İtirazım Var (2014)  
userId                                                                  
1                                             0.0                  0.0  
2                                             0.0                  0.0  
3                                             0.0    

In [30]:
movie_user_rating = user_movie_rating.values.T

In [31]:
movie_user_rating.shape

(9064, 671)

In [32]:
from sklearn.decomposition import TruncatedSVD

In [33]:
SVD = TruncatedSVD(n_components=12)
matrix = SVD.fit_transform(movie_user_rating)

In [34]:
matrix.shape

(9064, 12)

In [35]:
corr = np.corrcoef(matrix)

In [36]:
corr.shape

(9064, 9064)

In [37]:
corr

array([[ 1.        ,  0.27060785,  0.0595358 , ...,  0.40069489,
        -0.07093394,  0.1348526 ],
       [ 0.27060785,  1.        ,  0.02469086, ...,  0.21114592,
         0.79517845,  0.18651689],
       [ 0.0595358 ,  0.02469086,  1.        , ...,  0.4263909 ,
        -0.01640271, -0.03939324],
       ...,
       [ 0.40069489,  0.21114592,  0.4263909 , ...,  1.        ,
        -0.15466529, -0.02334381],
       [-0.07093394,  0.79517845, -0.01640271, ..., -0.15466529,
         1.        ,  0.32978288],
       [ 0.1348526 ,  0.18651689, -0.03939324, ..., -0.02334381,
         0.32978288,  1.        ]])

In [39]:
movie_title = user_movie_rating.columns
movie_title_list = list(movie_title)
query_index = movie_title_list.index('Guardians of the Galaxy (2014)')

In [40]:
query_index

3405

In [41]:
query = corr[query_index]

In [42]:
query

array([0.02082585, 0.24154453, 0.07571968, ..., 0.18948727, 0.28247951,
       0.86313605])

In [51]:
list(map(lambda x: movie_title_list[x], np.argsort(query)[::-1][:10]))

['Guardians of the Galaxy (2014)',
 'Iron Man 2 (2010)',
 'Edge of Tomorrow (2014)',
 'Avengers, The (2012)',
 'Indie Game: The Movie (2012)',
 'X-Men: Days of Future Past (2014)',
 'Captain America: The First Avenger (2011)',
 'Abduction (2011)',
 'Ghost Rider: Spirit of Vengeance (2012)',
 'TMNT (Teenage Mutant Ninja Turtles) (2007)']

In [52]:
ratings_df = pd.read_csv('data/ratings.csv')
movies_df = pd.read_csv('data/movies.csv')

In [59]:
user_movie_ratings_df = ratings_df.pivot_table('rating', index='userId', columns='movieId').fillna(0)

In [61]:
user_movie_ratings_matrix = user_movie_ratings_df.values

In [80]:
user_ratings_mean = np.mean(user_movie_ratings_matrix, axis=1)

In [89]:
user_mean_matrix = user_movie_ratings_matrix - user_ratings_mean.reshape(-1, 1)

In [90]:
user_mean_matrix

array([[-0.00562541, -0.00562541, -0.00562541, ..., -0.00562541,
        -0.00562541, -0.00562541],
       [-0.02923009, -0.02923009, -0.02923009, ..., -0.02923009,
        -0.02923009, -0.02923009],
       [-0.02007501, -0.02007501, -0.02007501, ..., -0.02007501,
        -0.02007501, -0.02007501],
       ...,
       [-0.01367748, -0.01367748, -0.01367748, ..., -0.01367748,
        -0.01367748, -0.01367748],
       [ 3.98698434, -0.01301566, -0.01301566, ..., -0.01301566,
        -0.01301566, -0.01301566],
       [ 4.95030885, -0.04969115, -0.04969115, ..., -0.04969115,
        -0.04969115, -0.04969115]])

In [91]:
from scipy.sparse.linalg import svds

In [92]:
U, sigma, Vt = svds(user_mean_matrix, k=12)

In [93]:
U.shape

(671, 12)

In [94]:
sigma.shape

(12,)

In [95]:
Vt.shape

(12, 9066)

In [96]:
sigma = np.diag(sigma)

In [97]:
sigma.shape

(12, 12)

In [103]:
pred_matrix = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)

In [105]:
pred_df = pd.DataFrame(pred_matrix, columns=user_movie_ratings_df.columns)

In [107]:
pred_df.head()

movieId    1         2         3         4         5         6         7       \
0       -0.079686  0.021779 -0.013837 -0.005870 -0.028877  0.032371  0.000715   
1        1.428452  1.608841  0.529476  0.168278  0.520809  1.107473  0.529719   
2        0.977246  0.396971  0.000299  0.027444  0.021287  0.141458 -0.057134   
3        1.870844  1.169993  0.252202  0.094831 -0.181713 -0.511953 -0.027820   
4        1.182777  0.924903  0.075998  0.061505  0.602680 -0.159825  0.339925   

movieId    8         9         10      ...    161084    161155    161594  \
0       -0.004428 -0.005219  0.038195  ... -0.004324 -0.004352  0.010478   
1        0.089376  0.296270  1.970031  ...  0.013227 -0.002275  0.020680   
2        0.031633 -0.012538  0.383576  ...  0.002761  0.004907 -0.014190   
3       -0.143080  0.013247  1.461694  ...  0.026412 -0.027245  0.054681   
4        0.081534 -0.079666  0.535018  ... -0.029124 -0.029357  0.009064   

movieId    161830    161918    161944    162376    162542    162672    163949  
0       -0.004256 -0.003944 -0.005674  0.018157 -0.005575 -0.005297 -0.003766  
1       -0.005245 -0.007644 -0.021019  0.031243 -0.000957 -0.000753  0.026901  
2       -0.000251 -0.006007 -0.003189 -0.026916  0.014637  0.013287 -0.005741  
3        0.018450  0.034544 -0.035740  0.088889 -0.019365 -0.017113  0.066559  
4       -0.029092 -0.030890 -0.057453  0.026344 -0.024027 -0.024614 -0.032752  

[5 rows x 9066 columns]